import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    position: 'relative',
  },
  containerLeafMode: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 24,
    paddingTop: 84,
    paddingBottom: 40,
    position: 'relative',
  },
  containerTreeMode: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    padding: 0,
  },
  authContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    padding: 24,
  },
  authPanel: {
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
    gap: 14,
  },
  authTitle: {
    color: '#0F172A',
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 40,
    marginBottom: 6,
  },
  authInput: {
    width: '100%',
    minHeight: 54,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '600',
    paddingHorizontal: 16,
  },
  authError: {
    color: '#DC2626',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  authPrimaryButton: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  authPrimaryButtonPressed: {
    backgroundColor: '#1D4ED8',
  },
  authButtonDisabled: {
    opacity: 0.72,
  },
  authPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  authSecondaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authSecondaryButtonText: {
    color: '#2563EB',
    fontSize: 15,
    fontWeight: '800',
  },
  syncBanner: {
    position: 'absolute',
    top: 10,
    left: 16,
    right: 16,
    minHeight: 34,
    borderRadius: 8,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    zIndex: 5000,
    elevation: 24,
  },
  syncBannerText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  floatingControls: {
    position: 'absolute',
    right: 24,
    bottom: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 6200,
    elevation: 34,
  },
  deleteCardFloatingControl: {
    position: 'absolute',
    right: -14,
    bottom: 118,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 6200,
    elevation: 34,
  },
  addFloatingControl: {
    position: 'absolute',
    left: '50%',
    bottom: -250,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateX: -180 }],
    zIndex: 1200,
    elevation: 4,
  },
  deck: {
    flex: 1,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  deckSlot: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'flex-start',
  },
  leafDeleteProgressOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2500,
    elevation: 30,
  },
  leafDeleteProgressRing: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#991B1B',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.24,
    shadowRadius: 4,
    elevation: 4,
  },
  leafDeleteProgressTickSlot: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 42,
    height: 42,
    alignItems: 'center',
  },
  leafDeleteProgressTick: {
    width: 2,
    height: 4,
    borderRadius: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
    marginTop: 1,
  },
  leafDeleteProgressTickActive: {
    backgroundColor: '#FFFFFF',
  },
  leafDeleteProgressCenter: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leafAddPreviewOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 18,
    alignItems: 'center',
    zIndex: 2400,
    elevation: 28,
  },
  leafAddPreviewCardFrame: {
    position: 'relative',
    width: '100%',
    minHeight: 360,
  },
  leafTrashIcon: {
    width: 13,
    height: 14,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  leafTrashIconLid: {
    width: 12,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#FFFFFF',
    marginBottom: 1,
  },
  leafTrashIconHandle: {
    position: 'absolute',
    top: 1,
    width: 5,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#FFFFFF',
  },
  leafTrashIconBody: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: '#FFFFFF',
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 2,
    paddingTop: 2,
  },
  leafTrashIconLine: {
    width: 1,
    height: 5,
    borderRadius: 1,
    backgroundColor: '#FFFFFF',
  },
  nodeView: {
    position: 'absolute',
    left: 14,
    width: '58%',
    bottom: 104,
    height: 220,
    backgroundColor: 'transparent',
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 0,
    padding: 14,
    shadowOpacity: 0,
    elevation: 0,
  },
  nodeViewCanvas: {
    position: 'relative',
    flex: 1,
    height: '100%',
    width: '100%',
    backgroundColor: 'transparent',
    borderRadius: 20,
    borderWidth: 0,
  },
  nodeViewMapLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  nodeViewMapNode: {
    position: 'absolute',
    width: 8,
    height: 8,
    marginLeft: -4,
    marginTop: -4,
    borderRadius: 4,
    backgroundColor: '#64748B',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  nodeViewMapNodeDone: {
    backgroundColor: '#CBD5E1',
    borderColor: '#F8FAFC',
    opacity: 0.78,
  },
  nodeViewMapNodeFocused: {
    width: 12,
    height: 12,
    marginLeft: -6,
    marginTop: -6,
    borderRadius: 6,
    backgroundColor: '#0EA5E9',
    borderWidth: 2,
    borderColor: '#DBEAFE',
  },
  nodeViewMapNodePreview: {
    width: 10,
    height: 10,
    marginLeft: -5,
    marginTop: -5,
    borderRadius: 5,
    backgroundColor: '#F97316',
    borderWidth: 2,
    borderColor: '#FFEDD5',
    opacity: 0.9,
  },
  nodeViewMapNodeDeleteTarget: {
    width: 14,
    height: 14,
    marginLeft: -7,
    marginTop: -7,
    borderRadius: 7,
    backgroundColor: '#DC2626',
    borderWidth: 2,
    borderColor: '#FEE2E2',
    opacity: 1,
  },
  nodeViewMapLinePreview: {
    backgroundColor: '#F97316',
    opacity: 0.75,
  },
  nodeViewMapLine: {
    position: 'absolute',
    height: 1,
    backgroundColor: '#94A3B8',
    opacity: 0.6,
  },
  treeScroll: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    paddingRight: 0,
    paddingLeft: 0,
    zIndex: 1,
  },
  treeViewport: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },
  treeContent: {
    alignItems: 'flex-start',
    paddingBottom: 96,
    paddingTop: 8,
  },
  treeHorizontalContent: {
    flexGrow: 1,
  },
  treeCanvas: {
    position: 'relative',
    pointerEvents: 'box-none',
    alignItems: 'flex-start',
  },
  treeCompletionCanvasWall: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    overflow: 'hidden',
    zIndex: 0,
  },
  treeCompletionCanvasImage: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0.9,
    resizeMode: 'stretch',
    zIndex: 0,
  },
  treeCompletionCanvasText: {
    position: 'absolute',
    color: '#475569',
    fontFamily: 'Kalam_400Regular',
    fontSize: 28,
    fontWeight: '400',
    lineHeight: 34,
    opacity: 0.72,
    zIndex: 1,
  },
  card: {
    minHeight: 360,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    shadowColor: '#0F172A',
    shadowOffset: {
      width: 0,
      height: 14,
    },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 12,
  },
  leafCard: {
    position: 'absolute',
    left: 0,
    right: 0,
  },
  leafCardFrame: {
    position: 'relative',
    width: '100%',
    minHeight: 360,
  },
  leafDoneStampButton: {
    position: 'absolute',
    top: 428,
    alignSelf: 'center',
    width: 88,
    height: 88,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1050,
    elevation: 13,
  },
  leafDoneStampButtonPressed: {
    opacity: 0.72,
  },
  leafDoneStampButtonDragging: {
    zIndex: 2150,
    elevation: 23,
  },
  leafDoneStampHitTarget: {
    position: 'absolute',
    top: 428,
    alignSelf: 'center',
    width: 88,
    height: 88,
    zIndex: 2200,
    elevation: 24,
  },
  leafDoneStampIcon: {
    width: 88,
    height: 88,
    opacity: 0.72,
    resizeMode: 'contain',
  },
  leafDoneStampIconToggleOff: {
    opacity: 0.3,
  },
  treeCard: {
    position: 'relative',
    width: 220,
    minHeight: 100,
    maxHeight: 116,
    padding: 12,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  treeCollapsedCard: {
    opacity: 0.98,
  },
  treePreviewCard: {
    borderColor: '#F97316',
    borderStyle: 'dashed',
    borderWidth: 2,
    backgroundColor: 'rgba(255, 247, 237, 0.84)',
    opacity: 0.92,
  },
  treeCardControls: {
    right: 8,
    bottom: 10,
    top: undefined,
    gap: 6,
    alignItems: 'flex-end',
    transform: [{ scale: 0.8 }],
  },
  treeCardText: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
    textAlign: 'left',
  },
  treePreviewCardText: {
    color: '#F97316',
  },
  treeCardInput: {
    minHeight: 66,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '700',
    textAlign: 'left',
    textAlignVertical: 'top',
    paddingTop: 0,
  },
  treeDependencyBar: {
    left: 10,
    right: 10,
    bottom: 8,
    gap: 6,
  },
  treeDependencyText: {
    fontSize: 10,
    fontWeight: '700',
  },
  leafContentSurface: {
    position: 'relative',
    flex: 1,
    width: '100%',
    minHeight: 284,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    paddingHorizontal: 6,
    paddingTop: 10,
  },
  leafContentLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  leafPlaceholder: {
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    opacity: 0.95,
  },
  leafContentScroll: {
    flex: 1,
    width: '100%',
  },
  leafContentScrollContent: {
    flexGrow: 1,
    paddingBottom: 16,
  },
  leafPeekCardText: {
    fontSize: 26,
    lineHeight: 38,
    fontWeight: '400',
    textAlign: 'center',
    width: '100%',
  },
  leafTextOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.34)',
    pointerEvents: 'none',
  },
  leafCardOverlayText: {
    textAlign: 'center',
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '400',
    color: '#0F172A',
    width: '100%',
  },
  leafFocusedText: {
    color: '#0F172A',
  },
  leafDoneStampOverlay: {
    position: 'absolute',
    width: 250,
    height: 250,
    left: '50%',
    top: '50%',
    marginLeft: -125,
    marginTop: -125,
    opacity: 0.64,
    resizeMode: 'contain',
    transform: [{ rotate: '-8deg' }],
    zIndex: 28,
    elevation: 28,
  },
  treeDoneStampOverlay: {
    position: 'absolute',
    width: 106,
    height: 106,
    left: '50%',
    top: '50%',
    marginLeft: -53,
    marginTop: -53,
    opacity: 0.6,
    resizeMode: 'contain',
    transform: [{ rotate: '-8deg' }],
    zIndex: 28,
    elevation: 28,
  },
  leafPlaceholderBar: {
    width: '88%',
    height: 12,
    borderRadius: 6,
    backgroundColor: '#CBD5E1',
    marginBottom: 2,
  },
  focusedCard: {
    borderColor: '#475569',
    borderWidth: 1,
    borderStyle: 'solid',
  },
  deleteFocusedCard: {
    borderColor: '#DC2626',
    shadowColor: '#DC2626',
    shadowOpacity: 0.38,
  },
  leafEditingCard: {
    borderColor: '#E2E8F0',
    borderWidth: 1,
  },
  cardControls: {
    position: 'absolute',
    top: 14,
    right: 14,
    flexDirection: 'row',
    gap: 8,
    zIndex: 2,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonPressed: {
    backgroundColor: '#2563EB',
  },
  linkButtonActive: {
    backgroundColor: '#7C3AED',
  },
  dangerButton: {
    backgroundColor: '#DC2626',
  },
  dangerButtonPressed: {
    backgroundColor: '#B91C1C',
  },
  iconButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  cardText: {
    color: '#0F172A',
    fontFamily: 'Kalam_400Regular',
    fontSize: 28,
    fontWeight: '400',
    lineHeight: 38,
    textAlign: 'left',
    width: '100%',
  },
  doneCardText: {
    color: '#9F9F9F',
  },
  emptyCardText: {
    color: '#94A3B8',
  },
  cardInputWrap: {
    width: '100%',
    alignSelf: 'stretch',
  },
  cardInput: {
    width: '100%',
    maxWidth: '100%',
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: '#0F172A',
    fontFamily: 'Kalam_400Regular',
    fontSize: 28,
    fontWeight: '400',
    lineHeight: 34,
    padding: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    textAlign: 'left',
    textAlignVertical: 'top',
    flexWrap: 'wrap',
  },
  leafCardInput: {
    flex: 1,
    minHeight: 274,
    maxHeight: 274,
  },
  dependencyBar: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dependencyText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '800',
  },
  fab: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 12,
  },
  fabPressed: {
    backgroundColor: '#1D4ED8',
    transform: [{ scale: 0.96 }],
  },
  addCardControl: {
    width: 360,
    height: 360,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    transform: [{ scale: 1 }],
  },
  addCardControlPressed: {
    transform: [{ scale: 0.96 }],
  },
  addCardButtonShell: {
    width: 320,
    height: 320,
    borderRadius: 8,
    shadowColor: '#0F172A',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 16,
  },
  addCardButton: {
    width: 320,
    height: 320,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  addCardButtonImage: {
    position: 'absolute',
    top: 5,
    left: 5,
    width: 310,
    height: 310,
    opacity: 0.9,
    resizeMode: 'contain',
  },
  addCardButtonBackImage: {
    transform: [{ rotate: '-90deg' }],
  },
  addCardFace: {
    position: 'absolute',
    top: 0,
    left: 0,
    backfaceVisibility: 'hidden',
  },
  deleteCardButton: {
    width: 56,
    height: 56,
    borderRadius: 8,
    backgroundColor: '#DC2626',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 18,
  },
  deleteCardButtonPressed: {
    backgroundColor: '#B91C1C',
    transform: [
      { scale: 0.97 },
    ],
  },
  deleteCardIcon: {
    width: 42,
    height: 42,
    opacity: 0.9,
    resizeMode: 'contain',
  },
});
