import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  containerLeafMode: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 40,
    position: 'relative',
  },
  containerTreeMode: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    padding: 0,
  },
  floatingControls: {
    position: 'absolute',
    right: 24,
    bottom: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deck: {
    flex: 1,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  nodeView: {
    position: 'absolute',
    right: 16,
    bottom: 110,
    width: 176,
    height: 132,
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  nodeViewCanvas: {
    position: 'relative',
    flex: 1,
    marginHorizontal: 8,
    marginVertical: 8,
    height: 94,
    width: 160,
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  nodeViewMapNode: {
    position: 'absolute',
    width: 8,
    height: 8,
    marginLeft: -4,
    marginTop: -4,
    borderRadius: 4,
    backgroundColor: '#64748B',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  nodeViewMapNodeFocused: {
    width: 12,
    height: 12,
    marginLeft: -6,
    marginTop: -6,
    borderRadius: 6,
    backgroundColor: '#0EA5E9',
    borderWidth: 2,
    borderColor: '#DBEAFE',
  },
  nodeViewMapLine: {
    position: 'absolute',
    height: 1,
    backgroundColor: '#94A3B8',
    opacity: 0.6,
    transformOrigin: 'left center',
  },
  treeScroll: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    paddingRight: 0,
    paddingLeft: 0,
  },
  treeViewport: {
    flex: 1,
    width: '100%',
  },
  treeContent: {
    alignItems: 'flex-start',
    paddingBottom: 96,
    paddingTop: 8,
  },
  treeHorizontalContent: {
    flexGrow: 1,
  },
  treeCanvas: {
    position: 'relative',
    pointerEvents: 'box-none',
    alignItems: 'flex-start',
  },
  card: {
    minHeight: 360,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    shadowColor: '#0F172A',
    shadowOffset: {
      width: 0,
      height: 14,
    },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 12,
  },
  leafCard: {
    position: 'absolute',
    left: 0,
    right: 0,
  },
  treeCard: {
    position: 'relative',
    width: 240,
    minHeight: 110,
    maxHeight: 130,
    padding: 16,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  treeCollapsedCard: {
    opacity: 0.98,
  },
  treeCardControls: {
    right: 8,
    bottom: 10,
    top: undefined,
    gap: 6,
    alignItems: 'flex-end',
    transform: [{ scale: 0.8 }],
  },
  treeCardText: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
    textAlign: 'left',
  },
  treeCardInput: {
    minHeight: 72,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '700',
    textAlign: 'left',
    textAlignVertical: 'top',
    paddingTop: 0,
  },
  treeDependencyBar: {
    left: 10,
    right: 10,
    bottom: 8,
    gap: 6,
  },
  treeDependencyText: {
    fontSize: 10,
    fontWeight: '700',
  },
  focusedCard: {
    borderColor: '#0EA5E9',
    borderWidth: 4,
    shadowColor: '#0EA5E9',
    shadowOpacity: 0.3,
    elevation: 14,
  },
  leafEditingCard: {
    top: 0,
    zIndex: 2500,
    transform: [
      { scale: 1 },
      { rotate: '0deg' },
    ],
    borderColor: '#2563EB',
    borderWidth: 2,
  },
  cardControls: {
    position: 'absolute',
    top: 14,
    right: 14,
    flexDirection: 'row',
    gap: 8,
    zIndex: 2,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconButtonPressed: {
    backgroundColor: '#2563EB',
  },
  linkButtonActive: {
    backgroundColor: '#7C3AED',
  },
  dangerButton: {
    backgroundColor: '#DC2626',
  },
  dangerButtonPressed: {
    backgroundColor: '#B91C1C',
  },
  iconButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  cardText: {
    color: '#0F172A',
    fontSize: 32,
    fontWeight: '800',
    lineHeight: 40,
    textAlign: 'center',
  },
  emptyCardText: {
    color: '#94A3B8',
  },
  cardInput: {
    width: '100%',
    minHeight: 180,
    color: '#0F172A',
    fontSize: 32,
    fontWeight: '800',
    lineHeight: 40,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  dependencyBar: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dependencyText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '800',
  },
  fab: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 12,
  },
  fabPressed: {
    backgroundColor: '#1D4ED8',
    transform: [{ scale: 0.96 }],
  },
  modeFab: {
    backgroundColor: '#0F172A',
  },
  modeFabPressed: {
    backgroundColor: '#334155',
    transform: [{ scale: 0.96 }],
  },
  modeFabText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 26,
  },
  fabIcon: {
    color: '#FFFFFF',
    fontSize: 38,
    fontWeight: '500',
    lineHeight: 42,
    marginTop: -2,
  },
});
